inherits: stack.yml

features:
  num_workers: 8

model:
  base_models:
    - id: cat_lr025
      name: catboost
      params:
        task_type: GPU
        devices: "0"
        iterations: 8000
        early_stopping_rounds: 300
        learning_rate: 0.025
        depth: 7
        l2_leaf_reg: 2.0
        min_data_in_leaf: 15
        border_count: 254
        random_strength: 0.2
        bootstrap_type: Bernoulli
        subsample: 0.8
    - id: cat_lr020
      name: catboost
      params:
        task_type: GPU
        devices: "0"
        iterations: 8000
        early_stopping_rounds: 300
        learning_rate: 0.020
        depth: 7
        l2_leaf_reg: 2.0
        min_data_in_leaf: 15
        border_count: 254
        random_strength: 0.2
        bootstrap_type: Bernoulli
        subsample: 0.8
    - id: cat_lr030
      name: catboost
      params:
        task_type: GPU
        devices: "0"
        iterations: 8000
        early_stopping_rounds: 300
        learning_rate: 0.030
        depth: 7
        l2_leaf_reg: 2.0
        min_data_in_leaf: 15
        border_count: 254
        random_strength: 0.2
        bootstrap_type: Bernoulli
        subsample: 0.8
    - id: xgb_lr025
      name: xgboost
      params:
        n_estimators: 8000
        early_stopping_rounds: 300
        learning_rate: 0.025
        max_depth: 7
        min_child_weight: 15
        max_bin: 256
        tree_method: hist
        device: cuda
        sampling_method: gradient_based
        subsample: 0.8
        colsample_bytree: 0.8
        reg_alpha: 0.05
        reg_lambda: 3.0
    - id: xgb_lr020
      name: xgboost
      params:
        n_estimators: 8000
        early_stopping_rounds: 300
        learning_rate: 0.020
        max_depth: 7
        min_child_weight: 15
        max_bin: 256
        tree_method: hist
        device: cuda
        sampling_method: gradient_based
        subsample: 0.8
        colsample_bytree: 0.8
        reg_alpha: 0.05
        reg_lambda: 3.0
    - id: xgb_lr030
      name: xgboost
      params:
        n_estimators: 8000
        early_stopping_rounds: 300
        learning_rate: 0.030
        max_depth: 7
        min_child_weight: 15
        max_bin: 256
        tree_method: hist
        device: cuda
        sampling_method: gradient_based
        subsample: 0.8
        colsample_bytree: 0.8
        reg_alpha: 0.05
        reg_lambda: 3.0

validation:
  final_model_strategy: fold_average

postprocess:
  notebook_blend:
    pf_column: pf_ancc
    alpha_range: [0.95, 1.05, 0.01]
    tau_range: [40, 120, 5]
    w_pf_range: [0, 0.15, 0.01]

tracking:
  clearml:
    tags: [rogii, kaggle, stack, dwt, gpu]
